package gitlet;

import java.io.Serializable;

// a specialized data structure for storing filename and its hashcode generated by SHA1
public class NBtable implements Serializable {

    private String FullName;
    private String SHA1Value;

    public NBtable(String Fullname, String SHA1value){
        FullName = Fullname;
        SHA1Value = SHA1value;
    }

    public Boolean findSHA(String SHA1){
        if(SHA1Value.equals(SHA1)){
            return true;
        }else{
            return false;
        }
    }

    public Boolean findName(String filename){
        if(FullName.equals(filename)){
            return true;
        }else{
            return false;
        }
    }

    public static Boolean FileNameinNBArray(String filename, NBtable[] NBArray){  // find blob commit
        for(NBtable NB : NBArray){
            if(NB.findName(filename)){
                return true;
            }
        }
        return false;
    }

    public static Boolean SHAinNBArray(String Sha1, NBtable[] NBArray){  // find blob commit
        for(NBtable NB : NBArray){
            if(NB.findSHA(Sha1)){
                return true;
            }
        }
        return false;
    }

    public String getFullName() {
        return FullName;
    }

    public String getSHA1Value() {
        return SHA1Value;
    }

    public void setSHA1Value(String newSHA) {
        this.SHA1Value = newSHA;
    }

    public void setFullName(String fullName) {
        FullName = fullName;
    }
}
