package gitlet;
// a specialized data structure for storing filename and its hashcode generated by SHA1
public class NBtable {

    private String FullName;
    private String SHA1Value;

    public NBtable(String Fullname, String SHA1value){
        FullName = Fullname;
        SHA1Value = SHA1value;
    }

    public Boolean findSHA(String SHA1){
        if(SHA1Value.equals(SHA1)){
            return true;
        }else{
            return false;
        }
    }

    public Boolean findName(String filename){
        if(FullName.equals(filename)){
            return true;
        }else{
            return false;
        }
    }

    public String getFullName() {
        return FullName;
    }

    public String getSHA1Value() {
        return SHA1Value;
    }


}
